name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'
    
jobs:
  github-build-push:
    runs-on: self-hosted
    container:
      image: alpine:3.22
    steps:

    - uses: actions/checkout@v4
    - name: Install docker
      run: | 
        apk update
        apk add --update docker openrc
        rc-update add docker boot

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_PUSH_SECRET }}

    - name: Install Node.js and TypeScript
      run: | 
        apk update
        apk add --no-cache nodejs npm
        npm install -g typescript

    - name: Compile TS
      run: |
        npm install -g typescript
        tsc public/reattachListeners.ts
        tsc public/persistence.ts

    - name: Build and tag the Docker image
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        docker build . --file Dockerfile \
          --tag ghcr.io/itsachance/3an:${VERSION} \
          --tag ghcr.io/itsachance/3an:latest
        
    - name: Push the Docker image
      run: |
        VERSION=${GITHUB_REF#refs/tags/}
        docker push ghcr.io/itsachance/3an:${VERSION}
        docker push ghcr.io/itsachance/3an:latest
